### ISSUE TITLE
Basic hello world example

### ISSUE THREAD

**Issue by nailuj29** [ominitay/zigvale#12]
I'm trying to make a basic kernel that just prints "Hello World" to the terminal, but nothing is printed to the screen. Is there anywhere I can find an example of the proper usage of this library?

**Comment by ominitay** [comment]
I don't have an example kernel running on Zigvale on GitHub yet, I do intend to add one soon.

**Comment by ominitay** [comment]
I'd recommend looking at some C examples until then, such as https://github.com/limine-bootloader/limine-barebones/blob/master/stivale2-barebones/kernel/kernel.c :)

**Comment by nailuj29** [comment]
I managed to get something working at https://github.com/nailuj29gaming/zigvale-barebones

~~I just need to add a README and LICENSE and~~ you can link to it if you want

**Comment by ominitay** [comment]
Thank you for that! I think I'm going to roll my own though, just for the reason that I'd like to test out some new changes :)

**Comment by ominitay** [comment]
Example kernel is now available at https://github.com/ominitay/zigvale-barebones
