### ISSUE TITLE
`u1` instead of `bool`

### ISSUE THREAD

**Issue by leecannon** [ominitay/zigvale#16]
Is there any reason why you have prefered to use `u1` instead of `bool` in packed structs?

**Comment by ominitay** [comment]
I don't think so. In the C headers, flags are of the type `u64`, and individual bits are set within them, so my mental model was likely operating in terms of individual bits. I don't think it makes a difference either way though. Do you think it should be changed?

**Comment by leecannon** [comment]
I was just wondering as it felt weird to do things like the below but its not important.
```zig
.flags = .{
    .higher_half = 1,
    .pmr = 1,
    .fully_virtual_mapping = 1,
},
```

**Comment by ominitay** [comment]
Going to close this if that's ok? After thinking about and discussing it, I feel it's more natural to use a `u1` than a `bool` in the context of a bit field.
