### ISSUE TITLE
Missing `Kernel base address structure tag`

### ISSUE THREAD

**Issue by leecannon** [ominitay/zigvale#28]
This bootloader to kernel tag is missing: https://github.com/stivale/stivale/blob/master/STIVALE2.md#kernel-base-address-structure-tag

**Comment by ominitay** [comment]
Looking back, this was missed out when merging #9. I'll let you implement it if you want, otherwise I'll handle it when I get the time.

**Comment by ominitay** [comment]
Will merge from the dev branch once I get a chance to test it, or when you are happy.

**Comment by ominitay** [comment]
Oh apologies, seems I forgot about this @leecannon. Will get this merged into main unless you object :)

**Comment by leecannon** [comment]
Yea, this is good to merge.

Although I have bit the bullet and switched to limine boot protocol 😞

**Comment by ominitay** [comment]
It's a shame that Mint decided to fragment the osdev community by doing this...
